version: 2
project_name: poketactix

before:
  hooks:
    - go mod download

builds:
  - id: cli
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksums:
  name_template: "checksums.txt"

changelog:
  use: github

release:
  draft: false
  prerelease: false
